---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r, import and clean}
set.seed(1)
data("rest_inspec")
inspection_df = 
  rest_inspec %>% 
  select(score, boro, grade, violation_code) %>% 
  filter(!is.na(score), 
         boro != "Missing", 
         grade %in% c("A", "B", "C")) %>% 
  rename(Violation = violation_code,
         Grade = grade,
         Score = score,
         Borough = boro) %>% 
  mutate(Borough = str_to_title(Borough)) %>% 
  sample_n(5000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Distribution of Inspection Score Across NYC Boroughs

```{r, borough score}
inspection_df %>% 
  select(Borough, Score) %>%
  plot_ly(y = ~Score, color = ~Borough, type = "box",
          colors = "Set2")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Letter Grades For Restaurant Inspection Across NYC Boroughs

```{r, borough grade}
inspection_df %>% 
  select(Grade, Borough) %>% 
  count(Grade, Borough) %>% 
  plot_ly(x = ~Grade, y = ~n, color = ~Borough, type = "bar", colors = "Set2")
```

### Total Number of Restaurants by Inspection Letter Grade and Score

```{r, score and grade}
inspection_df %>% 
  select(Score, Grade) %>% 
  count(Score, Grade) %>% 
  plot_ly(x = ~n, y = ~Score, color = ~Grade, type = "scatter", colors = "Set2")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Total Number of Violations by Violation Code

```{r, violations}
inspection_df %>%
  select(Violation) %>% 
  count(Violation) %>% 
  mutate(Violation = fct_reorder(Violation, n)) %>% 
  plot_ly(x = ~Violation, y = ~n, color = ~Violation, type = "bar", colors = "Set2")
```